# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
    app.repository.path:
        class: Infrastructure\ODM\Repository\PathsRepository
        arguments: ['@doctrine.odm.mongodb.document_manager']
    app.use_case.get_path:
        class: Domain\UseCase\GetPath
        arguments: ['@app.repository.path']
    app.use_case.get_paths:
        class: Domain\UseCase\GetPaths
        arguments: ['@app.repository.path']
    app.use_case.add_path:
        class: Domain\UseCase\AddPath
        arguments: ['@app.repository.path']
    app.use_case.add_path_goal:
        class: Domain\UseCase\AddGoal
        arguments: ['@app.repository.path']
    app.use_case.remove_path_goal:
        class: Domain\UseCase\RemoveGoal
        arguments: ['@app.repository.path']
    app.use_case.edit_path_goal:
        class: Domain\UseCase\EditGoal
        arguments: ['@app.repository.path']
    app.use_case.add_path_goal_comment:
        class: Domain\UseCase\AddComment
        arguments: ['@app.repository.path']
