Domain\Model\Goal:
    type: embeddedDocument
    fields:
        id:
            type: string
            id: true
            strategy: NONE
        name:
            type: string
        icon:
            type: string
        description:
            type: string
        level:
            type: int
        order:
            type: int
        unread:
            type: int
        dueDate:
            type: date
            serialized_name: dueDate
        achievedDate:
            type: date
            serialized_name: achievedDate
        achieved:
            type: boolean
        lastNotificationSent:
            type: int
    embedMany:
        comments:
            targetDocument: Domain\Model\Comment
            strategy: setArray
        steps:
            targetDocument: Domain\Model\Step
            strategy: setArray
